### ISSUE TITLE
Problems when building the packer image

### ISSUE THREAD

**Issue by jhedev** [giantswarm/shipyard#11]
I'm having trouble building the packer image. With the setup (i.e. `minikube.json`) in the repo k8s does not seem to come up.

I have tried updating minikube to v0.30.0 and v0.31.0 which results in the failure attached below.

Any ideas what I should try?

```
    amazon-ebs: Moving files into cluster...
    amazon-ebs: Downloading kubeadm v1.10.0
    amazon-ebs: Downloading kubelet v1.10.0
    amazon-ebs: Finished Downloading kubelet v1.10.0
    amazon-ebs: Finished Downloading kubeadm v1.10.0
    amazon-ebs: Setting up certs...
    amazon-ebs: Connecting to cluster...
    amazon-ebs: Setting up kubeconfig...
    amazon-ebs: Starting cluster components...
    amazon-ebs: ================================================================================
    amazon-ebs: An error has occurred. Would you like to opt in to sending anonymized crash
    amazon-ebs: information to minikube to help prevent future errors?
    amazon-ebs: E1220 10:05:02.678053   15517 start.go:297] Error starting cluster:  kubeadm init error
    amazon-ebs: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
    amazon-ebs: To opt out of these messages, run the command:
    amazon-ebs: sudo /usr/bin/kubeadm alpha phase addon kube-dns
    amazon-ebs:  running command: : running command:
    amazon-ebs: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
    amazon-ebs: 	minikube config set WantReportErrorPrompt false
    amazon-ebs: ================================================================================
    amazon-ebs: sudo /usr/bin/kubeadm alpha phase addon kube-dns
    amazon-ebs:
    amazon-ebs:  output: [init] Using Kubernetes version: v1.10.0
    amazon-ebs: [init] Using Authorization modes: [Node RBAC]
    amazon-ebs: [preflight] Running pre-flight checks.
    amazon-ebs: [preflight] The system verification failed. Printing the output from the verification:
    amazon-ebs: KERNEL_VERSION: 4.4.0-1022-aws
    amazon-ebs: CONFIG_NAMESPACES: enabled
    amazon-ebs: CONFIG_NET_NS: enabled
    amazon-ebs: CONFIG_PID_NS: enabled
    amazon-ebs: CONFIG_IPC_NS: enabled
    amazon-ebs: CONFIG_UTS_NS: enabled
    amazon-ebs: CONFIG_CGROUPS: enabled
    amazon-ebs: CONFIG_CGROUP_CPUACCT: enabled
    amazon-ebs: CONFIG_CGROUP_DEVICE: enabled
    amazon-ebs: CONFIG_CGROUP_FREEZER: enabled
    amazon-ebs: CONFIG_CGROUP_SCHED: enabled
    amazon-ebs: CONFIG_CPUSETS: enabled
    amazon-ebs: CONFIG_MEMCG: enabled
    amazon-ebs: CONFIG_INET: enabled
    amazon-ebs: CONFIG_EXT4_FS: enabled
    amazon-ebs: CONFIG_PROC_FS: enabled
    amazon-ebs: CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
    amazon-ebs: CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
    amazon-ebs: CONFIG_OVERLAY_FS: enabled (as module)
    amazon-ebs: CONFIG_AUFS_FS: enabled (as module)
    amazon-ebs: CONFIG_BLK_DEV_DM: enabled
    amazon-ebs: DOCKER_VERSION: 18.09.0
    amazon-ebs: OS: Linux
    amazon-ebs: CGROUPS_CPU: enabled
    amazon-ebs: CGROUPS_CPUACCT: enabled
    amazon-ebs: CGROUPS_CPUSET: enabled
    amazon-ebs: CGROUPS_DEVICES: enabled
    amazon-ebs: CGROUPS_FREEZER: enabled
    amazon-ebs: CGROUPS_MEMORY: enabled
    amazon-ebs: 	[WARNING Hostname]: hostname "minikube" could not be reached
    amazon-ebs: 	[WARNING Hostname]: hostname "minikube" lookup minikube on 172.31.0.2:53: no such host
    amazon-ebs: 	[WARNING FileExisting-ebtables]: ebtables not found in system path
    amazon-ebs: 	[WARNING FileExisting-crictl]: crictl not found in system path
    amazon-ebs: Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
    amazon-ebs: Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
    amazon-ebs: 	[WARNING ExtraArgs]: kube-apiserver: failed to parse extra argument --Authorization.Mode=RBAC
    amazon-ebs: [preflight] Some fatal errors occurred:
    amazon-ebs: 	[ERROR SystemVerification]: unsupported docker version: 18.09.0
    amazon-ebs: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
    amazon-ebs: : running command:
    amazon-ebs: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
    amazon-ebs: sudo /usr/bin/kubeadm alpha phase addon kube-dns
```
